### PR TITLE
feat: rename no-ssr to client-only

### LINKED ISSUE #20: Proposal: Renaming to Client-Only
[Issuehunt badges](https://issuehunt.io/r/egoist/vue-no-ssr/issues/20)

Hey there,

As you know, we are using `<no-ssr>` in Nuxt.js and after looking at this PR (https://github.com/nuxt/nuxt.js/pull/5941), I do believe the right naming should be `<client-only>`.

I know that VuePress actually uses this naming as well: https://vuepress.vuejs.org/guide/using-vue.html#browser-api-access-restrictions

What do you think?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/egoist/vue-no-ssr/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by Atinux**
Closes #20 

Let me know what you think @egoist

### CODE REVIEW

**Comment by egoist** [comment]
Don't forget to claim your bounty on IssueHunt 😄

**Comment by Atinux** [comment]
Will do 😁

**Comment by Atinux** [comment]
Submitted @egoist : https://issuehunt.io/r/egoist/vue-no-ssr/issues/20

I don't know how it works afterward 😄

**Pull request merged**
